print("I will now count my chickens: ")
#计算加减乘除取余的优先计算
print("Hens:", 25+30/6)
print("Rooster:",100 - 25 * 3 % 4 )
print("I will now count the eggs:")
print(3+3+1-5+4%2-1/4+6)
#比较值与加减的优先级，并输出真或否
print("Is it true that 3+2<5-7?")
print(3+2<5-7)
print("What is 3+2?",3+2)
print("What is 5-7?",5-7)
print("Oh,that't why it's false.")
print("How about some more.")
print("Is it greater?",5>-2)
print("Is it greater or equal?",5>=-2)
print("Is it less or equal?",5<=-2)